# prefork MPM
# StartServers: number of server processes to start
# MinSpareServers: minimum number of server processes which are kept spare
# MaxSpareServers: maximum number of server processes which are kept spare
# MaxRequestWorkers: maximum number of server processes allowed to start
# MaxConnectionsPerChild: maximum number of requests a server process serves
# MaxRequestsPerChild: sets the limit on the number of requests that an individual child server process will handle. After MaxRequestsPerChild requests, the child process will die. If MaxRequestsPerChild is 0, then the process will never expire.

StartServers            4
MinSpareServers         2
MaxSpareServers         8
MaxRequestWorkers       256
MaxConnectionsPerChild  0
MaxRequestsPerChild     256
